replicaCount: 1

image:
  repository: quay.io/keycloak/keycloak
  tag: latest
  imagePullPolicy: Always

service:
  type: NodePort
  ports:
    http: 8080
    https: 8443
  nodePorts:
    http: 32064
    https: 32065

env:
  DB_VENDOR: POSTGRES
  DB_ADDR: 192.168.1.128
  DB_PORT: "5432"
  DB_DATABASE: keycloak
  DB_USER: postgres
  DB_PASSWORD: "123456"
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  KC_HOSTNAME_STRICT_HTTPS: "false"

extraEnv: |
  - name: KC_FEATURES
    value: "token-exchange,admin-fine-grained-authz"

imagePullSecrets:
  - name: regcred

resources: {}

nodeSelector: {}
