apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "keycloak.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: {{ .Values.service.ports.http }}
      nodePort: {{ .Values.service.nodePorts.http }}
    - name: https
      port: {{ .Values.service.ports.https }}
      targetPort: {{ .Values.service.ports.https }}
      nodePort: {{ .Values.service.nodePorts.https }}
  selector:
    app.kubernetes.io/name: {{ include "keycloak.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
